// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0AeNSzcKmGBQKwWaIojdcMNFYqNFHa00',
    appId: '1:975764919396:web:e4ba8776b7f86fa927bb71',
    messagingSenderId: '975764919396',
    projectId: 'insusafe-131bc',
    authDomain: 'insusafe-131bc.firebaseapp.com',
    storageBucket: 'insusafe-131bc.firebasestorage.app',
    measurementId: 'G-14G8QVQ7NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcPOPFo7DZNpajz-2gxEBakKhvevjRy6w',
    appId: '1:975764919396:android:2a942fb6cca1ade127bb71',
    messagingSenderId: '975764919396',
    projectId: 'insusafe-131bc',
    storageBucket: 'insusafe-131bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq7gkP5HgeRsH7F-F4bJ3fTyEJ8l5ZI30',
    appId: '1:975764919396:ios:2b83642a42121ca527bb71',
    messagingSenderId: '975764919396',
    projectId: 'insusafe-131bc',
    storageBucket: 'insusafe-131bc.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq7gkP5HgeRsH7F-F4bJ3fTyEJ8l5ZI30',
    appId: '1:975764919396:ios:2b83642a42121ca527bb71',
    messagingSenderId: '975764919396',
    projectId: 'insusafe-131bc',
    storageBucket: 'insusafe-131bc.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0AeNSzcKmGBQKwWaIojdcMNFYqNFHa00',
    appId: '1:975764919396:web:d8884358446c991227bb71',
    messagingSenderId: '975764919396',
    projectId: 'insusafe-131bc',
    authDomain: 'insusafe-131bc.firebaseapp.com',
    storageBucket: 'insusafe-131bc.firebasestorage.app',
    measurementId: 'G-E9VTTHJMBP',
  );
}
