name: InsuSafe
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  flutter_slidable:  ^3.0.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.5
  firebase_database: ^10.4.0
  fl_chart: ^0.69.0
  intl: ^0.19.0
  cloud_firestore: ^4.15.5
  cloud_functions: ^4.6.0
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.3.0
  barcode_scan2: ^4.5.1
  slide_to_act: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/img.png
    - assets/patient_picture/11539820.png